"""
Add transcoding models
Create Date: 2025-12-15 13:56:36.937846
"""

import sqlalchemy as sa

from alembic import op

revision = "e5c9c4723eb6"
down_revision = "cef18c8c350f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transcoding_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("video_codec", sa.String(), nullable=False),
        sa.Column("max_video_bitrate", sa.Integer(), nullable=True),
        sa.Column("audio_codec", sa.String(), nullable=False),
        sa.Column("max_audio_bitrate", sa.Integer(), nullable=True),
        sa.Column("container", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "transcoding_session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("media_file_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "output_format",
            sa.Enum("HLS", "PROGRESSIVE", name="transcodingformat"),
            nullable=False,
        ),
        sa.Column("video_codec", sa.String(), nullable=True),
        sa.Column("audio_codec", sa.String(), nullable=True),
        sa.Column("audio_track_index", sa.Integer(), nullable=True),
        sa.Column("subtitle_track_index", sa.Integer(), nullable=True),
        sa.Column("burn_subtitles", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="transcodingstatus",
            ),
            nullable=False,
        ),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("output_path", sa.String(), nullable=True),
        sa.Column("manifest_path", sa.String(), nullable=True),
        sa.Column("process_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transcoding_session_session_id"),
        "transcoding_session",
        ["session_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_transcoding_session_session_id"), table_name="transcoding_session"
    )
    op.drop_table("transcoding_session")
    op.drop_table("transcoding_profile")
    # ### end Alembic commands ###
