"""
add_library_type_to_library_path
Create Date: 2025-12-09 13:43:41.577729
"""

import sqlalchemy as sa

from alembic import op

revision = "20e8100b27e2"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "librarypath",
        sa.Column("library_type", sa.String(), nullable=False, server_default="movie"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("librarypath", "library_type")
    # ### end Alembic commands ###
