"""
Migrate from hashed_password to password field with PasswordType
Create Date: 2025-12-08 23:47:16.161181
"""

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op

revision = "de7e724ff7d9"
down_revision = "ebe15e7f3dce"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "password",
            sqlalchemy_utils.types.password.PasswordType(
                schemes=["pbkdf2_sha512", "md5_crypt"],
                deprecated=["md5_crypt"],
            ),
            nullable=True,
        ),
    )
    op.drop_column("user", "hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("hashed_password", sa.VARCHAR(), nullable=False))
    op.drop_column("user", "password")
    # ### end Alembic commands ###
