"""
Add enhanced metadata fields for transcoding
Create Date: 2025-12-15 23:29:46.104369
"""

import sqlalchemy as sa

from alembic import op

revision = "56b821d1d285"
down_revision = "cef18c8c350f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("audio_track", sa.Column("sample_rate", sa.Integer(), nullable=True))
    op.add_column("video_track", sa.Column("profile", sa.String(), nullable=True))
    op.add_column("video_track", sa.Column("level", sa.String(), nullable=True))
    op.add_column("video_track", sa.Column("pixel_format", sa.String(), nullable=True))
    op.add_column("video_track", sa.Column("bit_depth", sa.Integer(), nullable=True))
    op.add_column("video_track", sa.Column("color_range", sa.String(), nullable=True))
    op.add_column("video_track", sa.Column("color_space", sa.String(), nullable=True))
    op.add_column(
        "video_track", sa.Column("color_primaries", sa.String(), nullable=True)
    )
    op.add_column(
        "video_track", sa.Column("color_transfer", sa.String(), nullable=True)
    )
    op.add_column(
        "video_track", sa.Column("max_luminance", sa.Integer(), nullable=True)
    )
    op.add_column("video_track", sa.Column("min_luminance", sa.Float(), nullable=True))
    op.add_column("video_track", sa.Column("max_cll", sa.Integer(), nullable=True))
    op.add_column("video_track", sa.Column("max_fall", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("video_track", "max_fall")
    op.drop_column("video_track", "max_cll")
    op.drop_column("video_track", "min_luminance")
    op.drop_column("video_track", "max_luminance")
    op.drop_column("video_track", "color_transfer")
    op.drop_column("video_track", "color_primaries")
    op.drop_column("video_track", "color_space")
    op.drop_column("video_track", "color_range")
    op.drop_column("video_track", "bit_depth")
    op.drop_column("video_track", "pixel_format")
    op.drop_column("video_track", "level")
    op.drop_column("video_track", "profile")
    op.drop_column("audio_track", "sample_rate")
    # ### end Alembic commands ###
