name: "Setup Dependencies"
description: "Install all dependencies for Ferelix server (backend + frontend)"

inputs:
  install-backend:
    description: "Install backend (Python) dependencies"
    required: false
    default: "true"
  install-frontend:
    description: "Install frontend (Node.js) dependencies"
    required: false
    default: "true"
  install-e2e:
    description: "Install E2E (Playwright) dependencies"
    required: false
    default: "false"
  install-ffmpeg:
    description: "Install FFmpeg"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install just
      uses: extractions/setup-just@v3

    # Backend setup
    - name: Install uv
      if: inputs.install-backend == 'true'
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        cache-dependency-glob: "server/uv.lock"

    - name: Set up Python
      if: inputs.install-backend == 'true'
      shell: bash
      run: uv python install 3.14

    - name: Install backend dependencies
      if: inputs.install-backend == 'true'
      shell: bash
      working-directory: server
      run: uv sync --all-groups

    # Frontend setup
    - name: Install pnpm
      if: inputs.install-frontend == 'true'
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Set up Node.js
      if: inputs.install-frontend == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: "22"
        cache: "pnpm"
        cache-dependency-path: "web/pnpm-lock.yaml"

    - name: Install frontend dependencies
      if: inputs.install-frontend == 'true'
      shell: bash
      working-directory: web
      run: pnpm install

    # E2E setup
    - name: Install E2E dependencies
      if: inputs.install-e2e == 'true'
      shell: bash
      working-directory: e2e
      run: |
        npm install
        npx playwright install --with-deps chromium

    # FFmpeg setup
    - name: Install FFmpeg
      if: inputs.install-ffmpeg == 'true'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
