name: "Setup Dependencies"
description: "Install all dependencies for Ferelix server (backend + frontend)"

runs:
  using: "composite"
  steps:
    - name: Install just
      uses: extractions/setup-just@v3

    # Backend setup
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        cache-dependency-glob: "server/uv.lock"

    - name: Set up Python
      shell: bash
      run: uv python install 3.14

    - name: Install backend dependencies
      shell: bash
      working-directory: server
      run: uv sync

    # Frontend setup
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        package_json_file: web/package.json


    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        cache: "pnpm"
        cache-dependency-path: "web/pnpm-lock.yaml"

    - name: Install frontend dependencies
      shell: bash
      working-directory: web
      run: pnpm install
