"""
Add transcoding jobs table
Create Date: 2025-12-15 23:57:45.599664
"""

import sqlalchemy as sa

from alembic import op

revision = "6e8907acad12"
down_revision = "56b821d1d285"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transcoding_job",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("media_file_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("video_codec", sa.String(), nullable=True),
        sa.Column("audio_codec", sa.String(), nullable=True),
        sa.Column("video_bitrate", sa.Integer(), nullable=True),
        sa.Column("audio_bitrate", sa.Integer(), nullable=True),
        sa.Column("max_width", sa.Integer(), nullable=True),
        sa.Column("max_height", sa.Integer(), nullable=True),
        sa.Column("output_path", sa.String(), nullable=True),
        sa.Column("playlist_path", sa.String(), nullable=True),
        sa.Column("progress_percent", sa.Float(), nullable=True),
        sa.Column("transcoded_duration", sa.Float(), nullable=True),
        sa.Column("current_fps", sa.Float(), nullable=True),
        sa.Column("current_bitrate", sa.Integer(), nullable=True),
        sa.Column("process_id", sa.Integer(), nullable=True),
        sa.Column("ffmpeg_command", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("client_ip", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("last_accessed_at", sa.DateTime(), nullable=False),
        sa.Column("auto_cleanup", sa.Boolean(), nullable=False),
        sa.Column("keep_segments", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transcoding_job_media_file_id"),
        "transcoding_job",
        ["media_file_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transcoding_job_session_id"),
        "transcoding_job",
        ["session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transcoding_job_session_id"), table_name="transcoding_job")
    op.drop_index(op.f("ix_transcoding_job_media_file_id"), table_name="transcoding_job")
    op.drop_table("transcoding_job")
    # ### end Alembic commands ###
